spring:
  application:
    name: questboard
  datasource:
    url: jdbc:postgresql://localhost:5432/questboard
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false
    generate-ddl: false
    sql:
      init:
        platform: postgresql
    profiles:
      active: dev
server:
  port: 8080


